server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro_authorization?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

    hikari:
      allow-pool-suspension: true
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      driver-class-name: com.mysql.jdbc.Driver

  #thymeleaf模板引擎
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false

#  redis:
#    # Redis数据库索引（默认为 0）
#    database: 0
#    # Redis服务器地址
#    host: 127.0.0.1
#    # Redis服务器连接端口
#    port: 6379
#    # Redis 密码
#    password:
#    jedis:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 8
#        # 连接池中的最大空闲连接
#        max-idle: 500
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 2000
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 10000
#    # 连接超时时间（毫秒）
#    timeout: 0



mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.shiro.authentications.pojo
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE